repos:
  - repo: local
    hooks:
      - id: test:line-count
        name: line count
        entry: ./tests/line-count/run.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: test:multi-module:cjs
        name: multi module - cjs
        entry: ./tests/multi-module/cjs/run.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: test:multi-module:jsm
        name: multi module - jsm
        entry: ./tests/multi-module/jsm/run.sh
        language: system
        always_run: true
        pass_filenames: false
