repos:
  - repo: local
    hooks:
      - id: test:multi-module
        name: multi module
        entry: ./tests/multi-module/run.sh
        language: system
        always_run: true
        pass_filenames: false
